### ISSUE TITLE
Could not locate bindings file

### ISSUE THREAD

**Issue by MartijnR** [albanm/node-libxslt#37]
I ran into a weird issue on 2 out of 3 servers when upgrading to NodeJS 4.2.2. So far the only difference I found between these servers, is the linux kernel. (Good server: 3.13.0-14-generic, Bad servers: 3.13.0-57-generic and 3.13.0-43-generic). 

Npm version (2.14.7), NodeJS version (4.2.2), NPM's internal node-gyp version (3.0.3) are all the same.

I'm out of ideas at the moment. Is there anything else you can recommend I check?

This is the error. It occurs when starting the application after a successful `npm install`.
```
/home/enketo/enketo-express/node_modules/libxslt/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/enketo/enketo-express/node_modules/libxslt/node_modules/libxmljs-mt/build/xmljs.node
 → /home/enketo/enketo-express/node_modules/libxslt/node_modules/libxmljs-mt/build/Debug/xmljs.node
 → /home/enketo/enketo-express/node_modules/libxslt/node_modules/libxmljs-mt/build/Release/xmljs.node
 → /home/enketo/enketo-express/node_modules/libxslt/node_modules/libxmljs-mt/out/Debug/xmljs.node
 → /home/enketo/enketo-express/node_modules/libxslt/node_modules/libxmljs-mt/Debug/xmljs.node
 → /home/enketo/enketo-express/node_modules/libxslt/node_modules/libxmljs-mt/out/Release/xmljs.node
 → /home/enketo/enketo-express/node_modules/libxslt/node_modules/libxmljs-mt/Release/xmljs.node
 → /home/enketo/enketo-express/node_modules/libxslt/node_modules/libxmljs-mt/build/default/xmljs.node
 → /home/enketo/enketo-express/node_modules/libxslt/node_modules/libxmljs-mt/compiled/4.2.2/linux/x64/xmljs.node
    at bindings (/home/enketo/enketo-express/node_modules/libxslt/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/enketo/enketo-express/node_modules/libxslt/node_modules/libxmljs-mt/lib/bindings.js:1:99)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/enketo/enketo-express/node_modules/libxslt/node_modules/libxmljs-mt/index.js:4:16)
    at Module._compile (module.js:435:26)
```

**Comment by gagern** [comment]
After a clean `npm install` I find the file at `node_modules/libxmljs-mt/build/Release/xmljs.node`. Which is the third file listed in your log snippet. Can you please check whether the file is there? If not, can you please look at the relevant portion of the build log? On my system it looks like this:

```
> libxmljs-mt@0.14.5 install /home/mvg/src/up/node-libxslt/node_modules/libxmljs-mt
> node-gyp rebuild

make: Entering directory '/home/mvg/src/up/node-libxslt/node_modules/libxmljs-mt/build'
  CC(target) Release/obj.target/libxml/vendor/libxml/buf.o
  ⋮
  CXX(target) Release/obj.target/xmljs/src/xml_xpath_context.o
  SOLINK(target) Release/obj.target/xmljs.node
  COPY Release/xmljs.node
make: Leaving directory '…/node-libxslt/node_modules/libxmljs-mt/build'
```

**Comment by MartijnR** [comment]
Thanks @gagern.

Turns out libxslt never build (the `build` directory is missing under libxmljs-mt). I was fooled by the fact the npm install didn't output any errors. I suspect another package might be the cause of this (node-sass probably).

When I manually `npm uninstall libxslt && npm install libxslt` after `npm install`, it works. Yay.
