### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by cha55son** [albanm/node-libxslt#48]
I'm currently using this module along with node debugger and a watch task. Every time I change code and tests re-run I get this error message:

```
< Message:
<     Module did not self-register.
< Stack:
< Error: Module did not self-register.
<     at Error (native)
<     at Object.Module._extensions..node (module.js:440:18)
<     at Module.load (module.js:357:32)
<     at Function.Module._load (module.js:314:12)
<     at Module.require (module.js:367:17)
<     at require (internal/module.js:16:19)
<     at bindings (/Users/chason/Sites/pagijs/node_modules/bindings/bindings.js:76:44)
<     at Object.<anonymous> (/Users/chason/Sites/pagijs/node_modules/libxmljs-mt/lib/bindings.js:1:99)
<     at Module._compile (module.js:413:34)
<     at Object.Module._extensions..js (module.js:422:10)
```

Any idea how I can fix it?

**Comment by cha55son** [comment]
Node v5.8.0
NPM 3.7.3
Mac 10.11.3

**Comment by cha55son** [comment]
Found this issue! Here's my setup:

```
var gulp = require('gulp');
var mocha = require('gulp-mocha');

gulp.task('watch', function () {
    var watcher = gulp.watch(['src/**/*.js', 'test/**/*.js'], ['build']);
    return gulp.src('test/**/*-test.js')
               .pipe(mocha({ reporter: 'nyan' }));
});
```

According to this link: https://github.com/sindresorhus/gulp-mocha/issues/86 Mocha is clearing the require cache causing the original issue. Adding `var libxslt = require('libxslt');` to the top of my gulp file fixed the issue.

Hope this helps anyone else that runs into this issue.
