### ISSUE TITLE
Error when trying to update to node 16

### ISSUE THREAD

**Issue by codingchefs** [albanm/node-libxslt#87]
Hi,

Currently, my project is on node 12. The library works fine. But when I upgrade to node 16, it throws an error when I try to install the library.

Any idea how to resolve it?

```
7022 error make: *** No rule to make target `Release/obj.target/libexslt/deps/libxslt/libexslt/common.o', needed by `Release/exslt.a'. Stop.
7022 error gyp ERR! build error
7022 error gyp ERR! stack Error: `make` failed with exit code: 2
7022 error gyp ERR! stack at ChildProcess.onExit (/Users/xyz/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
7022 error gyp ERR! stack at ChildProcess.emit (node:events:390:28)
7022 error gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
7022 error gyp ERR! System Darwin 20.6.0
7022 error gyp ERR! command "/Users/xyz/.nvm/versions/node/v16.13.0/bin/node" "/Users/xyz/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
7022 error gyp ERR! cwd /Users/xyz/workspace/project/node_modules/libxslt
7022 error gyp ERR! node -v v16.13.0
7022 error gyp ERR! node-gyp -v v8.2.0
7022 error gyp ERR! not ok
```

Thanks

**Comment by lognaturel** [comment]
I haven't looked at this in detail but two things to note:
* Last I checked this didn't work with NPM 7 (https://github.com/albanm/node-libxslt/pull/84#issuecomment-888522211)
* It may not work on M1 Macs: https://github.com/albanm/node-libxslt/pull/86

**Comment by codingchefs** [comment]
Thanks for the response. 
I have npm version 6 and intel as processor for mac. or does it work with npm > 7?

**Comment by lognaturel** [comment]
Sounds like it's neither of the problems I listed, then. Sorry, I don't have any other ideas.

**Comment by codingchefs** [comment]
ok no problem. I will keep looking for any alternatives.

**Comment by dhammikab** [comment]
I was able to get this working (regular Intel MacOS), by explicitly installing node1-libxmljsmt-myh.

The steps I followed were: 

npm install libxslt
npm install node1-libxmljsmt-myh

**Comment by dianabarsan** [comment]
I'm also getting an error when trying to install on node 16 and npm 8: 
```
npm ERR! make: *** [node-libxslt.target.mk:159: Release/obj.target/node-libxslt.node] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/diana/projects/medic-utils/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.10.136-1-MANJARO
npm ERR! gyp ERR! command "/home/diana/.nvm/versions/node/v16.16.0/bin/node" "/home/diana/projects/medic-utils/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/diana/projects/medic-utils/exc/node_modules/libxslt
npm ERR! gyp ERR! node -v v16.16.0
npm ERR! gyp ERR! node-gyp -v v4.0.0
npm ERR! gyp ERR! not ok

```
Full logs: https://pastebin.com/RhYsCNW8

**Comment by lognaturel** [comment]
Please try with 0.10.2
